# Generated by Django 2.2.3 on 2019-12-02 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 3, 10, 11, 12, 366725)),
        ),
    ]
