# Generated by Django 2.2.3 on 2020-01-08 07:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191202_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 9, 7, 34, 42, 259268)),
        ),
    ]
