# Generated by Django 2.2.3 on 2019-07-28 23:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190712_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 23, 34, 42, 430815)),
        ),
    ]
