# Generated by Django 2.2.3 on 2019-07-21 15:22

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20190712_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 22, 15, 22, 54, 635243)),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='task_type_description',
            field=tinymce.models.HTMLField(verbose_name='content'),
        ),
    ]
