# Generated by Django 2.2.3 on 2020-01-09 04:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20200108_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 10, 4, 16, 7, 903613)),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tasktype',
            name='task_type_description',
            field=models.TextField(),
        ),
    ]
