# Generated by Django 2.2.3 on 2020-01-18 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20200109_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(default='2019-08-20 06:55:55'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default='2019-08-20 06:55:55'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(default='working on something'),
        ),
    ]
